---
# task file for Debian distribution

- name: debian is supported
  set_fact:
    launchpad_ppa_webupd8_os_supported: yes

- name: ensure the webupd8 launchpad apt repository key is present
  apt_key:
    id=0xC2518248EEA14886
    keyserver=keyserver.ubuntu.com
    state=present
  become: yes

- name: ensure the webupd8 launchpad apt repository is present
  apt_repository:
    repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'
    update_cache=yes
    state=present
  become: yes

- name: ensure the webupd8 launchpad source apt repository is present
  apt_repository:
    repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'
    update_cache=yes
    state=present
  become: yes
