---
# task file for Ubuntu distribution

- name: ubuntu is supported
  set_fact:
    launchpad_ppa_webupd8_os_supported: yes

- name: ensure the webupd8 launchpad apt repository is present
  apt_repository:
    repo='ppa:webupd8team/java'
    update_cache=yes
    state=present
  become: yes
